export default {
  title: 'Fantasy Crux 2.0',
  motto: 'Steel & Consequence',
  edition: 'Cold Iron Edition',
  description: 'Compact, gritty fantasy rules built for fast use at the table.',
  primaryNav: [
    { number: 0, label: 'Start Here', href: '/rules/start-here/' },
    { number: 1, label: 'Characters', href: '/rules/characters/' },
    { number: 2, label: 'Skills', href: '/rules/skills/' },
    { number: 3, label: 'Equipment', href: '/rules/equipment/' },
    { number: 4, label: 'Combat', href: '/rules/combat/' },
    { number: 5, label: 'Magic', href: '/rules/magic/' },
    { number: 6, label: 'Talents', href: '/rules/talents/' },
    { number: 7, label: 'Adventuring', href: '/rules/adventuring/' },
    { number: 8, label: 'GM Tools', href: '/rules/gm-tools/' },
    { number: 9, label: 'Creatures', href: '/rules/creatures/' },
    { number: 'QR', label: 'Reference', href: '/reference/' },
    { number: '§', label: 'License', href: '/license/' },
  ],
  quickGroups: [
    { id: 'core', label: 'Core procedure' },
    { id: 'characters', label: 'Characters' },
    { id: 'skills', label: 'Skills' },
    { id: 'equipment', label: 'Equipment' },
    { id: 'combat', label: 'Combat' },
    { id: 'magic', label: 'Magic' },
    { id: 'talents', label: 'Talents' },
    { id: 'adventuring', label: 'Adventuring' },
    { id: 'gm-tools', label: 'Gamemaster tools' },
  ],
};
